In [1]:
import numpy as np

# ZAD 1
### mnożenie macierzy przez wektor

In [2]:
A=np.array([[3, 4, 5],[1,2,3],[3,4,5]])

In [3]:
B=np.array([[1],[2],[3]])

In [4]:
print (A)

[[3 4 5]
 [1 2 3]
 [3 4 5]]


In [5]:
print (B)

[[1]
 [2]
 [3]]


In [6]:
def mm(X,Y):
    return X[0]*Y[0,0]+X[1]*Y[1,0]+X[2]*Y[2,0]

In [7]:
def matrix_vector(A, B):
    C=np.array(np.array([
        [mm(A[0,0:3],B)],
        [mm(A[1,0:3],B)],
        [mm(A[2,0:3],B)]]))
    return C

In [8]:
matrix_vector(A,B)

array([[26],
       [14],
       [26]])

# ZAD 3
### mnożenie rank-1 update

In [9]:
A=np.array([[3, 4, 5],[1,2,3],[3,4,5]])

In [10]:
print (A)

[[3 4 5]
 [1 2 3]
 [3 4 5]]


In [11]:
B=np.array([[1, 2, 3],[2, 3, 4],[3, 4, 5]])

In [12]:
print (B)

[[1 2 3]
 [2 3 4]
 [3 4 5]]


In [13]:
def rank_1(A,B):
    C=np.array([[0, 0, 0],[0,0,0],[0,0,0]])
    for k in range(3):
        for i in range(3):
            for j in range(3):
                C[i,j]+=A[i,k]*B[k,j]
    return C

In [14]:
rank_1(A,B)

array([[26, 38, 50],
       [14, 20, 26],
       [26, 38, 50]])